### PR TITLE
Added can function

### PR DESCRIPTION
**Pull request by bayanr**
I added a can function to check whether the user has permission without redirecting. Useful for special cases when handling lack of permissions.

### CODE REVIEW

**Comment by halfdan** [comment]
Hey @bayanr, this is great. I realise this PR is very old, but if you're up for it could you add some tests for this and we can merge it in?

**Comment by bayanr** [comment]
Wow I completely forgot about this. Tests are should be simple enough to add so I'll give it a try.

**Comment by bayanr** [comment]
@halfdan I rebased my branch and added a couple of tests, though I'm not really sure they're what you expect. Please let me know if you expect more/less/different tests.

**Review by halfdan — APPROVED** [review]

**Comment by bendamschke** [comment]
Hey @halfdan , any updates on this PR? Thanks!

**Review by halfdan — APPROVED** [review]

**Pull request merged**
